# Generated by Django 5.1.15 on 2026-09-26 22:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("ops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            (
                                "PERFORMANCE",
                                "Équipement pour l'amélioration des performances",
                            ),
                            ("OM_TOOLS", "Outils, matériel et pièces de rechange E&M"),
                            ("PPE", "Équipements de protection individuelle"),
                            ("LOGISTICS", "Logistique et déplacement"),
                            ("CHEMICAL", "Produits chimiques de traitement"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        blank=True,
                        help_text="Sous-rubrique Excel (ex. « 1. Distribution - Tuyaux »)",
                        max_length=160,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("unit", models.CharField(blank=True, max_length=30)),
                ("rented", models.BooleanField(blank=True, null=True)),
                (
                    "min_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "monthly_requirement",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "additional_need",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("source_ref", models.CharField(blank=True, max_length=255)),
                ("flags", models.JSONField(blank=True, default=list)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_items",
                        to="core.site",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "code"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("APP", "Application"),
                            ("IMPORT", "Import Excel"),
                            ("ADMIN", "Saisie bureau"),
                        ],
                        default="APP",
                        max_length=10,
                    ),
                ),
                ("source_ref", models.CharField(blank=True, max_length=255)),
                ("flags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("OPENING", "Stock initial"),
                            ("IN", "Entrée"),
                            ("OUT", "Sortie"),
                            ("ADJUST", "Ajustement d'inventaire"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Toujours positive sauf pour ADJUST",
                        max_digits=12,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=200)),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="ops.incident",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="stock.stockitem",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.site",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="ops.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
