# Generated by Django 5.1.15 on 2026-09-26 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyAggregate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                ("metric", models.CharField(max_length=60)),
                ("value", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTUAL", "Historique validé (mois clos)"),
                            ("PROVISIONAL", "Provisoire — non utilisé dans les KPI"),
                        ],
                        max_length=12,
                    ),
                ),
                ("source_ref", models.CharField(blank=True, max_length=255)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_aggregates",
                        to="core.site",
                    ),
                ),
            ],
            options={
                "ordering": ["site", "month", "metric"],
                "unique_together": {("site", "month", "metric")},
            },
        ),
    ]
