# Generated by Django 5.1.15 on 2026-09-26 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionPlanTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("code", models.CharField(blank=True, max_length=20)),
                ("section", models.CharField(blank=True, max_length=160)),
                ("title", models.CharField(max_length=200)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Journalière"),
                            ("WEEKLY", "Hebdomadaire"),
                            ("MONTHLY", "Mensuelle"),
                            ("PERIODIC", "Trimestrielle / semestrielle / annuelle"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start", models.DateField(blank=True, null=True)),
                ("end", models.DateField(blank=True, null=True)),
                ("duration_days", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "scheduled_dates",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Jours cochés dans le calendrier (ISO)",
                    ),
                ),
                (
                    "progress_pct",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("status_note", models.CharField(blank=True, max_length=200)),
                ("comment", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("source_ref", models.CharField(blank=True, max_length=255)),
                ("flags", models.JSONField(blank=True, default=list)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_tasks",
                        to="core.asset",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_tasks",
                        to="core.site",
                    ),
                ),
            ],
            options={
                "ordering": ["site", "year", "order"],
            },
        ),
        migrations.CreateModel(
            name="BudgetLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField(help_text="1er jour du mois budgété")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("STAFF", "Besoin en personnel"),
                            ("LOGISTICS", "Besoin logistique"),
                            ("TOOLS", "Besoin en outils et équipements"),
                            ("MATERIALS", "Besoin en matériels et matériaux"),
                            ("ENERGY", "Besoin énergie"),
                            ("COMMUNICATION", "Besoin en communication"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("activity", models.CharField(max_length=200)),
                ("purpose", models.TextField(blank=True)),
                (
                    "maintenance_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ROUTINE", "Exploitation de routine"),
                            ("URGENT", "Maintenance Urgente (MU)"),
                            ("CORRECTIVE", "Maintenance Corrective (MC)"),
                            ("PREVENTIVE", "Maintenance Préventive (MP)"),
                            ("SUPPORT", "Autres activités de support"),
                        ],
                        max_length=12,
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=20)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "unit_price_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("responsible", models.CharField(blank=True, max_length=160)),
                ("supplier", models.CharField(blank=True, max_length=160)),
                ("start", models.DateField(blank=True, null=True)),
                ("end", models.DateField(blank=True, null=True)),
                ("source_ref", models.CharField(blank=True, max_length=255)),
                ("flags", models.JSONField(blank=True, default=list)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budget_lines",
                        to="core.site",
                    ),
                ),
            ],
            options={
                "ordering": ["month", "category", "id"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                ("amount_usd", models.DecimalField(decimal_places=2, max_digits=12)),
                ("source_ref", models.CharField(blank=True, max_length=255)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monthly_budgets",
                        to="core.site",
                    ),
                ),
            ],
            options={
                "unique_together": {("site", "month")},
            },
        ),
        migrations.CreateModel(
            name="Tariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ELECTRICITY", "Électricité (USD/kWh)"),
                            ("FUEL", "Carburant (USD/L)"),
                        ],
                        max_length=12,
                    ),
                ),
                ("price_usd", models.DecimalField(decimal_places=4, max_digits=8)),
                ("valid_from", models.DateField()),
                ("source_ref", models.CharField(blank=True, max_length=255)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tariffs",
                        to="core.site",
                    ),
                ),
            ],
            options={
                "ordering": ["site", "kind", "-valid_from"],
                "unique_together": {("site", "kind", "valid_from")},
            },
        ),
    ]
