#!/usr/bin/env bash
# One-shot production install on a fresh Ubuntu 24.04 server (run as root; cloud-init calls it).
# Idempotent: re-running keeps the existing .env (secrets) and simply rebuilds/restarts the stack.
#   Usage: bash deploy/install.sh [domain]      (default: em.<public-ip-with-dashes>.sslip.io)
set -euo pipefail
cd "$(dirname "$0")/.."
APP_DIR="$(pwd)"

log() { echo "[ymejibu-install] $*"; }

# --- Docker ------------------------------------------------------------------------------
if ! docker compose version >/dev/null 2>&1; then
  log "Installation de Docker"
  apt-get update -y
  apt-get install -y ca-certificates curl
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  chmod a+r /etc/apt/keyrings/docker.asc
  . /etc/os-release
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu ${VERSION_CODENAME} stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -y
  apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  systemctl enable --now docker
fi

# --- Swap (the frontend build needs memory on small servers) ---------------------------------
if ! swapon --show | grep -q .; then
  log "Création d'un swap de 2 Go"
  fallocate -l 2G /swapfile && chmod 600 /swapfile && mkswap /swapfile && swapon /swapfile
  grep -q '^/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
fi

# --- Configuration (.env, generated once) ----------------------------------------------------
if [ ! -f .env ]; then
  DOMAIN="${1:-}"
  if [ -z "$DOMAIN" ]; then
    IP="$(curl -fsS --max-time 5 http://169.254.169.254/hetzner/v1/metadata/public-ipv4 || curl -fsS --max-time 5 https://api.ipify.org)"
    DOMAIN="em.${IP//./-}.sslip.io"
  fi
  log "Création de .env pour ${DOMAIN}"
  umask 077
  cat > .env <<ENV
# Generated by deploy/install.sh on $(date -Is). Keep this file secret (chmod 600).
COMPOSE_FILE=docker-compose.yml:deploy/docker-compose.prod.yml
DOMAIN=${DOMAIN}
WEB_BIND=127.0.0.1:8080
DJANGO_SECRET_KEY=$(openssl rand -base64 48 | tr -d '\n/+=')
DJANGO_DEBUG=0
DJANGO_ALLOWED_HOSTS=${DOMAIN}
DJANGO_CSRF_TRUSTED_ORIGINS=https://${DOMAIN}
DJANGO_BEHIND_HTTPS_PROXY=1
POSTGRES_PASSWORD=$(openssl rand -hex 24)
DEMO_PASSWORD=
# The Excel workbooks are imported explicitly after upload (see docs/guides/deploiement-hetzner.md).
IMPORT_ON_START=0
ENV
fi
chmod 600 .env

# --- Start -----------------------------------------------------------------------------------
log "Construction et démarrage des conteneurs"
docker compose up -d --build

# --- Daily backup at 02:30 (keeps 14 days in /var/backups/ymejibu) ----------------------------
cat > /etc/cron.d/ymejibu-backup <<CRON
30 2 * * * root cd ${APP_DIR} && ./scripts/sauvegarde.sh >> /var/log/ymejibu-backup.log 2>&1
CRON
chmod +x scripts/sauvegarde.sh

DOMAIN_NOW="$(grep '^DOMAIN=' .env | cut -d= -f2)"
log "Terminé. Adresse : https://${DOMAIN_NOW}  (le certificat peut prendre 1 à 2 minutes)"
