# Generated by Django 5.1.15 on 2026-09-26 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "timezone",
                    models.CharField(default="Africa/Lubumbashi", max_length=64),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffingNeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_ref", models.CharField(blank=True, max_length=255)),
                (
                    "raw_label",
                    models.CharField(
                        blank=True,
                        help_text="Libellé d'origine tel que saisi dans Excel",
                        max_length=255,
                    ),
                ),
                (
                    "flags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Anomalies détectées à l'import (codes du rapport qualité)",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("duties", models.TextField(blank=True)),
                ("headcount", models.PositiveIntegerField(blank=True, null=True)),
                ("permanent", models.BooleanField(blank=True, null=True)),
                ("duration_value", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "duration_unit",
                    models.CharField(
                        default="DAYS",
                        help_text="Unité non précisée dans Excel : à confirmer",
                        max_length=10,
                    ),
                ),
                ("start", models.DateField(blank=True, null=True)),
                ("end", models.DateField(blank=True, null=True)),
                ("comment", models.TextField(blank=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staffing_needs",
                        to="core.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=120)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zones",
                        to="core.site",
                    ),
                ),
            ],
            options={
                "ordering": ["site", "code"],
                "unique_together": {("site", "code")},
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_ref", models.CharField(blank=True, max_length=255)),
                (
                    "raw_label",
                    models.CharField(
                        blank=True,
                        help_text="Libellé d'origine tel que saisi dans Excel",
                        max_length=255,
                    ),
                ),
                (
                    "flags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Anomalies détectées à l'import (codes du rapport qualité)",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=160)),
                ("title", models.CharField(max_length=160)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("RESP_TECH", "Responsable technique"),
                            (
                                "ADJOINT",
                                "Responsable technique adjoint (opérations, stock, logistique)",
                            ),
                            ("ZONE_TECH", "Technicien de zone"),
                            ("PUMP_FOCAL", "Point focal pompage"),
                            ("STORAGE_FOCAL", "Point focal stockage"),
                            ("SSE", "Responsable SSE"),
                            ("DATA_OFFICER", "Responsable base de données"),
                            ("FUNDER", "Bailleur (lecture seule)"),
                            ("CONTRACTOR", "Prestataire (non permanent)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("duties", models.TextField(blank=True)),
                ("permanent", models.BooleanField(default=True)),
                ("contract_start", models.DateField(blank=True, null=True)),
                ("contract_end", models.DateField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="person",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="people",
                        to="core.site",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="people",
                        to="core.zone",
                    ),
                ),
            ],
            options={
                "ordering": ["site", "role", "title"],
            },
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_ref", models.CharField(blank=True, max_length=255)),
                (
                    "raw_label",
                    models.CharField(
                        blank=True,
                        help_text="Libellé d'origine tel que saisi dans Excel",
                        max_length=255,
                    ),
                ),
                (
                    "flags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Anomalies détectées à l'import (codes du rapport qualité)",
                    ),
                ),
                ("code", models.CharField(max_length=40)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("JUNCTION", "Nœud / chambre de vannes"),
                            ("SOURCE", "Source / lac"),
                            ("PUMP_STATION", "Station de pompage"),
                            ("RESERVOIR_OUTLET", "Sortie réservoir"),
                            ("OUTFALL", "Exutoire (trop-plein / vidange)"),
                            ("DELIVERY", "Point de livraison (BF / CP)"),
                        ],
                        default="JUNCTION",
                        max_length=20,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("GOOD", "Bon"),
                            ("FAIR", "Moyen"),
                            ("POOR", "Mauvais"),
                            ("OUT_OF_SERVICE", "Hors service"),
                            ("UNKNOWN", "Inconnu"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nodes",
                        to="core.site",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nodes",
                        to="core.zone",
                    ),
                ),
            ],
            options={
                "ordering": ["site", "code"],
                "unique_together": {("site", "code")},
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_ref", models.CharField(blank=True, max_length=255)),
                (
                    "raw_label",
                    models.CharField(
                        blank=True,
                        help_text="Libellé d'origine tel que saisi dans Excel",
                        max_length=255,
                    ),
                ),
                (
                    "flags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Anomalies détectées à l'import (codes du rapport qualité)",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("INTAKE", "Captage"),
                            ("PUMP", "Groupe motopompe"),
                            ("PUMP_STATION", "Station de pompage"),
                            ("CHLORINATION_UNIT", "Unité de chloration"),
                            ("DOSING_PUMP", "Pompe doseuse"),
                            ("TANK", "Cuve / bac"),
                            ("SOLAR_PANEL", "Panneau solaire"),
                            ("BATTERY", "Batterie"),
                            ("STORAGE_SITE", "Site de stockage"),
                            ("RESERVOIR", "Réservoir"),
                            ("KIOSK", "Borne fontaine (kiosque)"),
                            ("PRIVATE_CONNECTION", "Connexion privée"),
                            ("GENSET", "Groupe électrogène"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "altitude_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "capacity_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("capacity_unit", models.CharField(blank=True, max_length=20)),
                (
                    "power_kw",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "head_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("specs", models.TextField(blank=True)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("GOOD", "Bon"),
                            ("FAIR", "Moyen"),
                            ("POOR", "Mauvais"),
                            ("OUT_OF_SERVICE", "Hors service"),
                            ("UNKNOWN", "Inconnu"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                ("install_date", models.DateField(blank=True, null=True)),
                ("built_by", models.CharField(blank=True, max_length=120)),
                ("om_documents", models.CharField(blank=True, max_length=255)),
                (
                    "maintenance_frequency_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("last_maintenance", models.DateField(blank=True, null=True)),
                ("next_maintenance", models.DateField(blank=True, null=True)),
                (
                    "attributes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Attributs spécifiques au type (robinets, bénéficiaires, DN de raccordement…)",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="core.asset",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="core.node",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="core.person",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="core.site",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="core.zone",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Fitting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_ref", models.CharField(blank=True, max_length=255)),
                (
                    "raw_label",
                    models.CharField(
                        blank=True,
                        help_text="Libellé d'origine tel que saisi dans Excel",
                        max_length=255,
                    ),
                ),
                (
                    "flags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Anomalies détectées à l'import (codes du rapport qualité)",
                    ),
                ),
                ("description", models.CharField(max_length=160)),
                ("dn", models.PositiveIntegerField(blank=True, null=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("GOOD", "Bon"),
                            ("FAIR", "Moyen"),
                            ("POOR", "Mauvais"),
                            ("OUT_OF_SERVICE", "Hors service"),
                            ("UNKNOWN", "Inconnu"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fittings",
                        to="core.node",
                    ),
                ),
            ],
            options={
                "unique_together": {("node", "description")},
            },
        ),
        migrations.CreateModel(
            name="PipeSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_ref", models.CharField(blank=True, max_length=255)),
                (
                    "raw_label",
                    models.CharField(
                        blank=True,
                        help_text="Libellé d'origine tel que saisi dans Excel",
                        max_length=255,
                    ),
                ),
                (
                    "flags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Anomalies détectées à l'import (codes du rapport qualité)",
                    ),
                ),
                ("code", models.CharField(max_length=60)),
                ("dn", models.PositiveIntegerField(help_text="Diamètre nominal (mm)")),
                ("material", models.CharField(blank=True, max_length=40)),
                ("length_m", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("MAIN", "Conduite principale"),
                            ("OVERFLOW", "Trop-plein / vidange"),
                            ("SERVICE", "Branchement BF / CP"),
                            ("RISING", "Refoulement"),
                        ],
                        default="MAIN",
                        max_length=20,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("GOOD", "Bon"),
                            ("FAIR", "Moyen"),
                            ("POOR", "Mauvais"),
                            ("OUT_OF_SERVICE", "Hors service"),
                            ("UNKNOWN", "Inconnu"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "from_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="segments_out",
                        to="core.node",
                    ),
                ),
                (
                    "to_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="segments_in",
                        to="core.node",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pipe_segments",
                        to="core.site",
                    ),
                ),
            ],
            options={
                "ordering": ["site", "code"],
                "unique_together": {("site", "code")},
            },
        ),
    ]
