# Generated by Django 5.1.15 on 2026-09-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="source_ref",
            field=models.CharField(
                blank=True,
                help_text="Origine Excel : fichier!feuille!cellule",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="fitting",
            name="source_ref",
            field=models.CharField(
                blank=True,
                help_text="Origine Excel : fichier!feuille!cellule",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="source_ref",
            field=models.CharField(
                blank=True,
                help_text="Origine Excel : fichier!feuille!cellule",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="source_ref",
            field=models.CharField(
                blank=True,
                help_text="Origine Excel : fichier!feuille!cellule",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="pipesegment",
            name="source_ref",
            field=models.CharField(
                blank=True,
                help_text="Origine Excel : fichier!feuille!cellule",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="staffingneed",
            name="source_ref",
            field=models.CharField(
                blank=True,
                help_text="Origine Excel : fichier!feuille!cellule",
                max_length=255,
            ),
        ),
    ]
