# Generated by Django 5.1.15 on 2026-09-26 22:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("plan", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("APP", "Application"),
                            ("IMPORT", "Import Excel"),
                            ("ADMIN", "Saisie bureau"),
                        ],
                        default="APP",
                        max_length=10,
                    ),
                ),
                ("source_ref", models.CharField(blank=True, max_length=255)),
                ("flags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("POMPAGE", "Fiche journalière — Station de pompage"),
                            ("STOCKAGE", "Fiche journalière — Stockage"),
                            (
                                "RESEAU_BF",
                                "Fiche journalière — Réseau et bornes fontaines",
                            ),
                            ("PANNE", "Rapport de panne / incident"),
                            ("MP_POMPE", "Checklist maintenance préventive — Pompe"),
                            (
                                "MP_RESERVOIR",
                                "Checklist maintenance préventive — Réservoir",
                            ),
                            ("MP_RESEAU", "Checklist maintenance préventive — Réseau"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Soumis"),
                            ("VALIDATED", "Validé"),
                            ("REJECTED", "Rejeté"),
                        ],
                        default="SUBMITTED",
                        max_length=12,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("client_updated_at", models.DateTimeField(blank=True, null=True)),
                ("derivation_errors", models.JSONField(blank=True, default=list)),
                (
                    "assigned_number",
                    models.CharField(
                        blank=True,
                        help_text="Numéro d'incident attribué par le serveur (jamais par le téléphone)",
                        max_length=30,
                    ),
                ),
                (
                    "derived_keys",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[code actif, date] des relevés alimentés par cette fiche",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="core.asset",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.site",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="core.zone",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyReading",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("APP", "Application"),
                            ("IMPORT", "Import Excel"),
                            ("ADMIN", "Saisie bureau"),
                        ],
                        default="APP",
                        max_length=10,
                    ),
                ),
                ("source_ref", models.CharField(blank=True, max_length=255)),
                ("flags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("operator", models.CharField(blank=True, max_length=160)),
                (
                    "hours_run",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "pressure_bar",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "pressure_in_bar",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "pressure_out_bar",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "flow_m3h",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "current_a",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "volume_m3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Pompe : volume pompé ; BF : volume vendu",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "volume_in_m3",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "volume_out_m3",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "level_pct",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "kwh",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "fuel_l",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "chlorine_g",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="readings",
                        to="core.asset",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.site",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="ops.formsubmission",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "asset__code"],
            },
        ),
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("APP", "Application"),
                            ("IMPORT", "Import Excel"),
                            ("ADMIN", "Saisie bureau"),
                        ],
                        default="APP",
                        max_length=10,
                    ),
                ),
                ("source_ref", models.CharField(blank=True, max_length=255)),
                ("flags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("nature", models.TextField()),
                ("location", models.CharField(blank=True, max_length=200)),
                ("action_taken", models.TextField(blank=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.site",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.zone",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaints",
                        to="ops.formsubmission",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="attachments/%Y/%m/")),
                ("content_type", models.CharField(blank=True, max_length=60)),
                ("sha256", models.CharField(blank=True, db_index=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="ops.formsubmission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("APP", "Application"),
                            ("IMPORT", "Import Excel"),
                            ("ADMIN", "Saisie bureau"),
                        ],
                        default="APP",
                        max_length=10,
                    ),
                ),
                ("source_ref", models.CharField(blank=True, max_length=255)),
                ("flags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=30, unique=True)),
                ("detected_at", models.DateTimeField()),
                ("reported_by", models.CharField(blank=True, max_length=160)),
                ("location_detail", models.CharField(blank=True, max_length=255)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("incident_type", models.CharField(blank=True, max_length=120)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Faible"),
                            ("MEDIUM", "Moyenne"),
                            ("CRITICAL", "Critique"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("service_interrupted", models.BooleanField(default=False)),
                (
                    "downtime_cause",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PUMP_FAILURE", "Panne des pompes"),
                            ("PIPE_BURST", "Rupture des conduites"),
                            ("POWER_CUT", "Coupure d'électricité"),
                            ("PLANNED_MAINTENANCE", "Maintenance programmée"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "downtime_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                ("affected_zone", models.CharField(blank=True, max_length=160)),
                (
                    "affected_population",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "probable_cause",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("VANDALISM", "Vandalisme et vol"),
                            ("OVERPRESSURE", "Surpression"),
                            ("SHALLOW_PIPE", "Tuyau mal enfoui"),
                            ("ILLEGAL_CONNECTION", "Connexion illégale"),
                            (
                                "MISHANDLING",
                                "Mauvaise manipulation des accessoires par le technicien",
                            ),
                            ("POOR_PIPE_QUALITY", "Mauvaise qualité du tuyau"),
                            ("POOR_BACKFILL", "Mauvais remblai"),
                            ("GROUND_MOVEMENT", "Mouvement de terrain"),
                            ("POOR_INSTALLATION", "Mauvaise installation"),
                            ("WATER_HAMMER", "Coup de bélier"),
                            ("FAULTY_CONNECTION", "Connexion défectueuse"),
                            ("OTHER", "Autre / non déterminée"),
                        ],
                        max_length=25,
                    ),
                ),
                ("root_cause", models.TextField(blank=True)),
                (
                    "nrw_cause",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PIPE_LEAK", "Fuites physiques sur les conduites"),
                            ("PIPE_BURST", "Ruptures de conduites"),
                            (
                                "RESERVOIR_OVERFLOW",
                                "Débordements de réservoirs (trop-plein)",
                            ),
                            ("NETWORK_FLUSH", "Purges du réseau"),
                            ("DRAINING", "Vidanges"),
                            (
                                "RESERVOIR_CLEANING",
                                "Eau utilisée pour le nettoyage des réservoirs",
                            ),
                            (
                                "FIREFIGHTING",
                                "Eau utilisée pour la lutte contre les incendies",
                            ),
                            ("ILLEGAL_BRANCH", "Branchements illégaux"),
                            ("FAULTY_METER", "Compteurs défectueux"),
                            ("MISCALIBRATED_METER", "Compteurs mal calibrés"),
                            ("ILLEGAL_CONNECTION", "Connexions illégales"),
                            ("READING_ERROR", "Erreurs de relevé"),
                            (
                                "UNBILLED_CONSUMPTION",
                                "Volumes consommés mais non facturés",
                            ),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "estimated_loss_m3",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Exploitation de routine"),
                            ("URGENT", "Maintenance Urgente (MU)"),
                            ("CORRECTIVE", "Maintenance Corrective (MC)"),
                            ("PREVENTIVE", "Maintenance Préventive (MP)"),
                            ("SUPPORT", "Autres activités de support"),
                        ],
                        default="CORRECTIVE",
                        max_length=12,
                    ),
                ),
                ("intervention_start", models.DateTimeField(blank=True, null=True)),
                ("intervention_end", models.DateTimeField(blank=True, null=True)),
                ("team", models.TextField(blank=True)),
                ("materials_used", models.TextField(blank=True)),
                (
                    "cost_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Ouvert"),
                            ("IN_PROGRESS", "En cours"),
                            ("CLOSED", "Réparé / clôturé"),
                        ],
                        default="OPEN",
                        max_length=12,
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("verification", models.JSONField(blank=True, default=dict)),
                ("lessons", models.JSONField(blank=True, default=dict)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incidents",
                        to="core.asset",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incidents",
                        to="core.node",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.site",
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incident",
                        to="ops.formsubmission",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incidents",
                        to="core.zone",
                    ),
                ),
            ],
            options={
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="QualityThreshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parameter",
                    models.CharField(
                        choices=[
                            ("RESIDUAL_CHLORINE", "Chlore résiduel (mg/L)"),
                            ("TURBIDITY", "Turbidité (NTU)"),
                            ("ODOUR_COLOUR", "Odeur/couleur anormale"),
                            ("LAB", "Test laboratoire"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        blank=True, help_text="Vide = tous les points", max_length=30
                    ),
                ),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "to_confirm",
                    models.BooleanField(
                        default=True,
                        help_text="Valeur par défaut à valider par le Responsable technique",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.asset",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_thresholds",
                        to="core.site",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SafetyCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("APP", "Application"),
                            ("IMPORT", "Import Excel"),
                            ("ADMIN", "Saisie bureau"),
                        ],
                        default="APP",
                        max_length=10,
                    ),
                ),
                ("source_ref", models.CharField(blank=True, max_length=255)),
                ("flags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("item", models.CharField(max_length=120)),
                ("ok", models.BooleanField(null=True)),
                ("location", models.CharField(blank=True, max_length=160)),
                ("observation", models.TextField(blank=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="safety_checks",
                        to="core.asset",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.site",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safety_checks",
                        to="ops.formsubmission",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.zone",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WaterQualityTest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("APP", "Application"),
                            ("IMPORT", "Import Excel"),
                            ("ADMIN", "Saisie bureau"),
                        ],
                        default="APP",
                        max_length=10,
                    ),
                ),
                ("source_ref", models.CharField(blank=True, max_length=255)),
                ("flags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                (
                    "parameter",
                    models.CharField(
                        choices=[
                            ("RESIDUAL_CHLORINE", "Chlore résiduel (mg/L)"),
                            ("TURBIDITY", "Turbidité (NTU)"),
                            ("ODOUR_COLOUR", "Odeur/couleur anormale"),
                            ("LAB", "Test laboratoire"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("compliant", models.BooleanField(null=True)),
                ("is_lab", models.BooleanField(default=False)),
                ("corrective_action", models.TextField(blank=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quality_tests",
                        to="core.asset",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.site",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_tests",
                        to="ops.formsubmission",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("APP", "Application"),
                            ("IMPORT", "Import Excel"),
                            ("ADMIN", "Saisie bureau"),
                        ],
                        default="APP",
                        max_length=10,
                    ),
                ),
                ("source_ref", models.CharField(blank=True, max_length=255)),
                ("flags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Exploitation de routine"),
                            ("URGENT", "Maintenance Urgente (MU)"),
                            ("CORRECTIVE", "Maintenance Corrective (MC)"),
                            ("PREVENTIVE", "Maintenance Préventive (MP)"),
                            ("SUPPORT", "Autres activités de support"),
                        ],
                        default="PREVENTIVE",
                        max_length=12,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CAPTAGE", "Captage"),
                            ("POMPAGE", "Pompage"),
                            ("RESERVOIR", "Réservoir"),
                            ("RESEAU", "Réseau"),
                            ("BF", "Bornes-fontaines"),
                        ],
                        max_length=12,
                    ),
                ),
                ("planned_date", models.DateField()),
                ("done_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planifié"),
                            ("DONE", "Réalisé"),
                            ("CANCELLED", "Annulé"),
                        ],
                        default="PLANNED",
                        max_length=10,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("PLAN", "Plan annuel"),
                            ("MANUAL", "Saisie bureau"),
                            ("CHECKLIST", "Créé par une checklist (non planifié)"),
                        ],
                        default="MANUAL",
                        max_length=10,
                    ),
                ),
                (
                    "downtime_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "cost_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "findings",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Besoins de maintenance relevés (partie, matériel, MO, coût, échéance)",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_orders",
                        to="core.asset",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_orders",
                        to="ops.incident",
                    ),
                ),
                (
                    "plan_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_orders",
                        to="plan.actionplantask",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.site",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        help_text="Checklist qui a clôturé (ou créé) cet ordre de travail",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_orders",
                        to="ops.formsubmission",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_orders",
                        to="core.zone",
                    ),
                ),
            ],
            options={
                "ordering": ["-planned_date"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("APP", "Application"),
                            ("IMPORT", "Import Excel"),
                            ("ADMIN", "Saisie bureau"),
                        ],
                        default="APP",
                        max_length=10,
                    ),
                ),
                ("source_ref", models.CharField(blank=True, max_length=255)),
                ("flags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Exploitation de routine"),
                            ("URGENT", "Maintenance Urgente (MU)"),
                            ("CORRECTIVE", "Maintenance Corrective (MC)"),
                            ("PREVENTIVE", "Maintenance Préventive (MP)"),
                            ("SUPPORT", "Autres activités de support"),
                        ],
                        max_length=12,
                    ),
                ),
                ("amount_usd", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.site",
                    ),
                ),
                (
                    "incident",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense",
                        to="ops.incident",
                    ),
                ),
                (
                    "work_order",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense",
                        to="ops.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.AddIndex(
            model_name="formsubmission",
            index=models.Index(
                fields=["site", "form_type", "date"],
                name="ops_formsub_site_id_d1c856_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailyreading",
            unique_together={("asset", "date")},
        ),
    ]
