# Generated by Django 5.1.15 on 2026-09-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="flags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Codes du rapport qualité concernant cet enregistrement",
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="source",
            field=models.CharField(
                choices=[
                    ("APP", "Application"),
                    ("IMPORT", "Import Excel"),
                    ("ADMIN", "Saisie bureau"),
                ],
                default="APP",
                help_text="Origine de l'enregistrement",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="source_ref",
            field=models.CharField(
                blank=True,
                help_text="Origine Excel : fichier!feuille!cellule (import)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="dailyreading",
            name="flags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Codes du rapport qualité concernant cet enregistrement",
            ),
        ),
        migrations.AlterField(
            model_name="dailyreading",
            name="source",
            field=models.CharField(
                choices=[
                    ("APP", "Application"),
                    ("IMPORT", "Import Excel"),
                    ("ADMIN", "Saisie bureau"),
                ],
                default="APP",
                help_text="Origine de l'enregistrement",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="dailyreading",
            name="source_ref",
            field=models.CharField(
                blank=True,
                help_text="Origine Excel : fichier!feuille!cellule (import)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="flags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Codes du rapport qualité concernant cet enregistrement",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="source",
            field=models.CharField(
                choices=[
                    ("APP", "Application"),
                    ("IMPORT", "Import Excel"),
                    ("ADMIN", "Saisie bureau"),
                ],
                default="APP",
                help_text="Origine de l'enregistrement",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="source_ref",
            field=models.CharField(
                blank=True,
                help_text="Origine Excel : fichier!feuille!cellule (import)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="formsubmission",
            name="flags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Codes du rapport qualité concernant cet enregistrement",
            ),
        ),
        migrations.AlterField(
            model_name="formsubmission",
            name="source",
            field=models.CharField(
                choices=[
                    ("APP", "Application"),
                    ("IMPORT", "Import Excel"),
                    ("ADMIN", "Saisie bureau"),
                ],
                default="APP",
                help_text="Origine de l'enregistrement",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="formsubmission",
            name="source_ref",
            field=models.CharField(
                blank=True,
                help_text="Origine Excel : fichier!feuille!cellule (import)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="flags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Codes du rapport qualité concernant cet enregistrement",
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="source",
            field=models.CharField(
                choices=[
                    ("APP", "Application"),
                    ("IMPORT", "Import Excel"),
                    ("ADMIN", "Saisie bureau"),
                ],
                default="APP",
                help_text="Origine de l'enregistrement",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="source_ref",
            field=models.CharField(
                blank=True,
                help_text="Origine Excel : fichier!feuille!cellule (import)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="safetycheck",
            name="flags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Codes du rapport qualité concernant cet enregistrement",
            ),
        ),
        migrations.AlterField(
            model_name="safetycheck",
            name="source",
            field=models.CharField(
                choices=[
                    ("APP", "Application"),
                    ("IMPORT", "Import Excel"),
                    ("ADMIN", "Saisie bureau"),
                ],
                default="APP",
                help_text="Origine de l'enregistrement",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="safetycheck",
            name="source_ref",
            field=models.CharField(
                blank=True,
                help_text="Origine Excel : fichier!feuille!cellule (import)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="waterqualitytest",
            name="flags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Codes du rapport qualité concernant cet enregistrement",
            ),
        ),
        migrations.AlterField(
            model_name="waterqualitytest",
            name="source",
            field=models.CharField(
                choices=[
                    ("APP", "Application"),
                    ("IMPORT", "Import Excel"),
                    ("ADMIN", "Saisie bureau"),
                ],
                default="APP",
                help_text="Origine de l'enregistrement",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="waterqualitytest",
            name="source_ref",
            field=models.CharField(
                blank=True,
                help_text="Origine Excel : fichier!feuille!cellule (import)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="flags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Codes du rapport qualité concernant cet enregistrement",
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="source",
            field=models.CharField(
                choices=[
                    ("APP", "Application"),
                    ("IMPORT", "Import Excel"),
                    ("ADMIN", "Saisie bureau"),
                ],
                default="APP",
                help_text="Origine de l'enregistrement",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="source_ref",
            field=models.CharField(
                blank=True,
                help_text="Origine Excel : fichier!feuille!cellule (import)",
                max_length=255,
            ),
        ),
    ]
